# Create this file: .github/workflows/pacman.yml
name: Generate Pacman Animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates pacman eating dots animation from github contributions
      - name: generate pacman-contribution-graph.svg
        uses: Platane/snk@v3
        with:
          github_user_name: lakshithasenavirathna
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=yellow&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&animation_speed=1&background_color=oooo#0d1117
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=yellow&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&animation_speed=1&background_color=oooo#0d1117
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # push the content to output branch
      - name: push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
